---
- name: Ensure user bob is present with address information
  hosts: all
  tasks:
    - name: Bob user created with DA rights
      win_domain_user:
        name: Bob
        firstname: Smith
        password: B0bP4ssw0rd
        path: CN=Users,DC=int,DC=foresta,DC=local
        state: present
