---
- name: Ensure user bob is present with address information
  hosts: all
  tasks:
    - name: Bob user created with DA rights
      win_domain_user:
        name: "{{user_name}}"
        firstname: "{{first_name}}"
        password: "{{initial_password}}"
        path: "{{ou_path}}"
        state: present
