---
- name: Get Organizational Units
  hosts: all
  tasks:
    - name: Get Organizational Units
      win_shell:
      Get-ADOrganizationalUnit -Filter 'Name -like "*"' | Select-Object 'DistinguishedName' | Write-Output
