---
- name: Get Organizational Units
  hosts: all
  vars:
    ous:none
  tasks:
    - name: Get Organizational Units
      win_shell: C:\Scripts\Get-OUs.ps1
      register:ou_results
     -set_fact:ous={{ou_results.stdout_lines}}
      
