---
# vim: set ft=ansible et ts=2 sw=2:
#
# Create a new VM from a template

- name: VM from template
  hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: Create VM from template
      vmware_guest:
        hostname: "{{vc_hostname}}"
        username: "{{vc_username}}"
        password: "{{vc_password}}"
        validate_certs: false
        datacenter: VASAI
        name: VM001
        template: WinVMTemplate
        disk:
          - size_gb: "{{ disk_size | default(20) }}"
            type: thin
            datastore: LUN002
        networks:
          - name: VM Network                 
        hardware:
          memory_mb: "{{ vm_memory | default(1024) }}"
        wait_for_ip_address: false
        state: present
      register: newvm
