---
# vim: set ft=ansible et ts=2 sw=2:
#
# Create a new VM from a template

- name: VM from template
  hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: Create VM from template
      vmware_guest:
        validate_certs: false
        datacenter: VASAI
        folder: /
        name: VM001
        template: WinVMTemplate
        disk:
          - size_gb: "{{ disk_size | default(20) }}"
            type: thin
            datastore: LUN002
        networks:
          - name: DPortGroup01
            type: static
            ip: 192.168.44.85
            netmask: 255.255.255.0
            gateway: 192.168.44.1
            dns_servers: 192.168.44.8
        customization:
            autologon: yes
            dns_servers:
             - 192.168.44.8
             - 192.168.1.2
            domain: int.lokhand.local
            password: Atos@2020
        hardware:
          memory_mb: "{{ vm_memory | default(1024) }}"
        wait_for_ip_address: false
        state: poweredon
      register: newvm
